# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ymadc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ymadccontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_63bfd534a59a4010a8d0fa4803df9c3f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dee2dc24a4824b679c8721e9c96343ac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ymadccontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_63bfd534a59a4010a8d0fa4803df9c3f }}/mcr.microsoft.com/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ymadc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8334f980c4d44300a288b32320c074bf }}
        images: 'ymadccontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_63bfd534a59a4010a8d0fa4803df9c3f }}/mcr.microsoft.com/hello-world:${{ github.sha }}'